spring:
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql

  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''

  h2:
    console:
      enabled: 'true'
      path: /h2-console

  batch:
    jdbc:
      initialize-schema: always

  application:
    name: batch

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
